version: '3'
services: 
  rectangle-container:
    image: rectangle-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      