version: '3'
services: 
  rectangle-container:
    image: rectangle-image
    build:
      dockerfile: Dockerfile
    environment:
      - OVERRIDE_ConnectionStrings__MongoDB=mongodb://mongodb:27017
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    develop:
      watch:
        - action: rebuild
          path: .
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      